server:
  port: 8021
mq:
  env: local
order: #订单处理队列
  mq:
    exchange: #交换机名称
      name: ${mq.env}:order:mq:exchange
    queue: #队列名称
      name: ${mq.env}:order:mq:queue
    routing: #routingkey
      key: ${mq.env}:order:mq:routing:key
spring:
  #给项目来个名字
  application:
    name: mall-rabbitmq-provider
  #配置rabbitMq 服务器
  rabbitmq:
    listener:
      simple:
        concurrency: 5 #消费者数量
        max-concurrency: 10 #最大消费者数量
        prefetch: 1 #消费者每次从队列获取的消息数量。写多了，如果长时间得不到消费，数据就一直得不到处理
        acknowledge-mode: manual #消费接收确认机制-手动确认
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #虚拟host 可以不设置,使用server默认host
#    virtual-host: JCcccHost
      #消息确认配置项

      #确认消息已发送到交换机(Exchange)
#    publisher-confirms: true
#      #确认消息已发送到队列(Queue)
#    publisher-returns: true
#