canal:
  # instance 实例所在ip
  host: 127.0.0.1
  # tcp通信端口
  port: 11111
  # 账号  canal-admin application.yml 设置的
  username: canal
  # 密码
  password: canal
  #实例名称
  instance: example

spring:
  datasource:
    url: jdbc:mysql://${mall.datasource.ip}:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: ${mall.datasource.username}
    password: ${mall.datasource.password}
    driver-class-name: com.mysql.jdbc.Driver
management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: '*'